name: Build windows container

on:
  workflow_dispatch:
    
jobs:
  build-and-push:
    runs-on: windows-latest

    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ghcr.io
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: build-and-push
      run: |
        docker build .github\workflows\win\ -t ghcr.io/adamuso/simple_class_traits/windows-build-container
        docker push ghcr.io/adamuso/simple_class_traits/windows-build-container
